export { login, logout } from '../services/usuario-service/login.service'
export { perfil, cadastro } from '../services/usuario-service/usuario.service'
export { cadastroTime, pegarTimes} from '../services/time-service/cadastrar.time'
export { deletarTime } from '../services/time-service/deletar.time'
export { atualizarTime } from '../services/time-service/atualizar-time'
export { listarPartidas } from '../services/partidas-service/listar-partida.service'
export { criarPartida } from '../services/partidas-service/criar-partidas-service'
export { atualizarPartida } from './partidas-service/atualizar-partida-sevice'
export { partidasRecentes} from './partidas-service/partidas-recentes-service'
export { proximasPartidas } from './partidas-service/proximas-partidas-service'